package com.htsc.soa.service.queryinvestmentcourtaccount;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * OSB Service
 * 
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * QueryInvestmentCourtAccount_Service service = new QueryInvestmentCourtAccount_Service();
 * QueryInvestmentCourtAccountPtt portType = service.getQueryInvestmentCourtAccountPort();
 * portType.crmQueryInvestmentCourtAccount(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "QueryInvestmentCourtAccount_Service", targetNamespace = "http://soa.htsc.com/service/QueryInvestmentCourtAccount", wsdlLocation = "http://168.8.5.214:6002/EsbService/QueryInvestmentCourtAccount?wsdl")
public class QueryInvestmentCourtAccountService extends Service {

	private final static URL QUERYINVESTMENTCOURTACCOUNTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.htsc.soa.service.queryinvestmentcourtaccount.QueryInvestmentCourtAccountService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.htsc.soa.service.queryinvestmentcourtaccount.QueryInvestmentCourtAccountService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://168.8.5.214:6002/EsbService/QueryInvestmentCourtAccount?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://168.8.5.214:6002/EsbService/QueryInvestmentCourtAccount?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		QUERYINVESTMENTCOURTACCOUNTSERVICE_WSDL_LOCATION = url;
	}

	public QueryInvestmentCourtAccountService(URL wsdlLocation,
			QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public QueryInvestmentCourtAccountService() {
		super(QUERYINVESTMENTCOURTACCOUNTSERVICE_WSDL_LOCATION, new QName(
				"http://soa.htsc.com/service/QueryInvestmentCourtAccount",
				"QueryInvestmentCourtAccount_Service"));
	}

	/**
	 * 
	 * @return returns QueryInvestmentCourtAccountPtt
	 */
	@WebEndpoint(name = "QueryInvestmentCourtAccount_Port")
	public QueryInvestmentCourtAccountPtt getQueryInvestmentCourtAccountPort() {
		return super.getPort(new QName(
				"http://soa.htsc.com/service/QueryInvestmentCourtAccount",
				"QueryInvestmentCourtAccount_Port"),
				QueryInvestmentCourtAccountPtt.class);
	}

}
