package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.smswcfservice.CompositeType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IService1", targetNamespace = "http://tempuri.org/")
public interface IService1 {

	/**
	 * 
	 * @param value
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetData", action = "http://tempuri.org/IService1/GetData")
	@WebResult(name = "GetDataResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetData")
	@ResponseWrapper(localName = "GetDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataResponse")
	public String getData(
			@WebParam(name = "value", targetNamespace = "http://tempuri.org/") Integer value);

	/**
	 * 
	 * @param composite
	 * @return returns
	 *         org.datacontract.schemas._2004._07.smswcfservice.CompositeType
	 */
	@WebMethod(operationName = "GetDataUsingDataContract", action = "http://tempuri.org/IService1/GetDataUsingDataContract")
	@WebResult(name = "GetDataUsingDataContractResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetDataUsingDataContract", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataUsingDataContract")
	@ResponseWrapper(localName = "GetDataUsingDataContractResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataUsingDataContractResponse")
	public CompositeType getDataUsingDataContract(
			@WebParam(name = "composite", targetNamespace = "http://tempuri.org/") CompositeType composite);

	/**
	 * 
	 * @param content
	 * @param pwd
	 * @param sn
	 * @param phoneNumber
	 * @param ips
	 * @param afterMMAndCode
	 * @param code
	 * @param datetime
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SPSend", action = "http://tempuri.org/IService1/SPSend")
	@WebResult(name = "SPSendResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SPSend", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SPSend")
	@ResponseWrapper(localName = "SPSendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SPSendResponse")
	public String spSend(
			@WebParam(name = "sn", targetNamespace = "http://tempuri.org/") String sn,
			@WebParam(name = "pwd", targetNamespace = "http://tempuri.org/") String pwd,
			@WebParam(name = "phoneNumber", targetNamespace = "http://tempuri.org/") String phoneNumber,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content,
			@WebParam(name = "Code", targetNamespace = "http://tempuri.org/") String code,
			@WebParam(name = "AfterMMAndCode", targetNamespace = "http://tempuri.org/") String afterMMAndCode,
			@WebParam(name = "datetime", targetNamespace = "http://tempuri.org/") XMLGregorianCalendar datetime,
			@WebParam(name = "ips", targetNamespace = "http://tempuri.org/") String ips);

	/**
	 * 
	 * @param content
	 * @param afterUAndP
	 * @param phoneNumber
	 * @param userName
	 * @param password
	 * @return returns java.lang.Integer
	 */
	@WebMethod(operationName = "SMSSend", action = "http://tempuri.org/IService1/SMSSend")
	@WebResult(name = "SMSSendResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SMSSend", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SMSSend")
	@ResponseWrapper(localName = "SMSSendResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SMSSendResponse")
	public Integer smsSend(
			@WebParam(name = "UserName", targetNamespace = "http://tempuri.org/") String userName,
			@WebParam(name = "Password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "AfterUAndP", targetNamespace = "http://tempuri.org/") String afterUAndP,
			@WebParam(name = "phoneNumber", targetNamespace = "http://tempuri.org/") String phoneNumber,
			@WebParam(name = "content", targetNamespace = "http://tempuri.org/") String content);

}
