package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * Service1 service = new Service1();
 * IService1 portType = service.getBasicHttpBindingIService1();
 * portType.getData(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "Service1", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://sms.taopu1.com/Service1.svc?wsdl")
public class Service1 extends Service {

	private final static URL SERVICE1_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(org.tempuri.Service1.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.Service1.class.getResource(".");
			url = new URL(baseUrl, "http://sms.taopu1.com/Service1.svc?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://sms.taopu1.com/Service1.svc?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICE1_WSDL_LOCATION = url;
	}

	public Service1(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Service1() {
		super(SERVICE1_WSDL_LOCATION, new QName("http://tempuri.org/",
				"Service1"));
	}

	/**
	 * 
	 * @return returns IService1
	 */
	@WebEndpoint(name = "BasicHttpBinding_IService1")
	public IService1 getBasicHttpBindingIService1() {
		return super.getPort(new QName("http://tempuri.org/",
				"BasicHttpBinding_IService1"), IService1.class);
	}

}
