package news.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import news.service.ArrayOfComnotice;
import news.service.ArrayOfCxdd;
import news.service.ArrayOfGpgsxq;
import news.service.ArrayOfQygg;
import news.service.ArrayOfQyjbxx;
import news.service.ArrayOfQysjk;
import news.service.ArrayOfQytop;
import news.service.ArrayOfSsxx;
import news.service.ArrayOfZjjg;
import news.service.Cxdd;
import news.service.Qysjk;
import news.service.Ssxx;
import news.service.Zjjg;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebServicePortType", targetNamespace = "http://service.com")
public interface WebServicePortType {

	/**
	 * 
	 * @param in0
	 * @return returns com.service.Cxdd
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getCxddById", targetNamespace = "http://service.com", className = "com.service.GetCxddById")
	@ResponseWrapper(localName = "getCxddByIdResponse", targetNamespace = "http://service.com", className = "com.service.GetCxddByIdResponse")
	public Cxdd getCxddById(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0);

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns com.service.ArrayOfZjjg
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getListZjjg", targetNamespace = "http://service.com", className = "com.service.GetListZjjg")
	@ResponseWrapper(localName = "getListZjjgResponse", targetNamespace = "http://service.com", className = "com.service.GetListZjjgResponse")
	public ArrayOfZjjg getListZjjg(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0,
			@WebParam(name = "in1", targetNamespace = "http://service.com") int in1);

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "zjjgCount", targetNamespace = "http://service.com", className = "com.service.ZjjgCount")
	@ResponseWrapper(localName = "zjjgCountResponse", targetNamespace = "http://service.com", className = "com.service.ZjjgCountResponse")
	public int zjjgCount();

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns com.service.ArrayOfQysjk
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getQysjk1", targetNamespace = "http://service.com", className = "com.service.GetQysjk1")
	@ResponseWrapper(localName = "getQysjk1Response", targetNamespace = "http://service.com", className = "com.service.GetQysjk1Response")
	public ArrayOfQysjk getQysjk1(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0,
			@WebParam(name = "in1", targetNamespace = "http://service.com") int in1);

	/**
	 * 
	 * @param in0
	 * @return returns com.service.ArrayOfQytop
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getQytop", targetNamespace = "http://service.com", className = "com.service.GetQytop")
	@ResponseWrapper(localName = "getQytopResponse", targetNamespace = "http://service.com", className = "com.service.GetQytopResponse")
	public ArrayOfQytop getQytop(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0);

	/**
	 * 
	 * @return returns com.service.ArrayOfCxdd
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getListCxdd", targetNamespace = "http://service.com", className = "com.service.GetListCxdd")
	@ResponseWrapper(localName = "getListCxddResponse", targetNamespace = "http://service.com", className = "com.service.GetListCxddResponse")
	public ArrayOfCxdd getListCxdd();

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "ssxxCount", targetNamespace = "http://service.com", className = "com.service.SsxxCount")
	@ResponseWrapper(localName = "ssxxCountResponse", targetNamespace = "http://service.com", className = "com.service.SsxxCountResponse")
	public int ssxxCount();

	/**
	 * 
	 * @param in2
	 * @param in1
	 * @param in0
	 * @return returns com.service.ArrayOfCxdd
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getListCxdd2", targetNamespace = "http://service.com", className = "com.service.GetListCxdd2")
	@ResponseWrapper(localName = "getListCxdd2Response", targetNamespace = "http://service.com", className = "com.service.GetListCxdd2Response")
	public ArrayOfCxdd getListCxdd2(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0,
			@WebParam(name = "in1", targetNamespace = "http://service.com") int in1,
			@WebParam(name = "in2", targetNamespace = "http://service.com") String in2);

	/**
	 * 
	 * @param in0
	 * @return returns com.service.ArrayOfCxdd
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getListCxdd1", targetNamespace = "http://service.com", className = "com.service.GetListCxdd1")
	@ResponseWrapper(localName = "getListCxdd1Response", targetNamespace = "http://service.com", className = "com.service.GetListCxdd1Response")
	public ArrayOfCxdd getListCxdd1(
			@WebParam(name = "in0", targetNamespace = "http://service.com") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.service.Ssxx
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getSsxxById", targetNamespace = "http://service.com", className = "com.service.GetSsxxById")
	@ResponseWrapper(localName = "getSsxxByIdResponse", targetNamespace = "http://service.com", className = "com.service.GetSsxxByIdResponse")
	public Ssxx getSsxxById(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0);

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "cxddCount", targetNamespace = "http://service.com", className = "com.service.CxddCount")
	@ResponseWrapper(localName = "cxddCountResponse", targetNamespace = "http://service.com", className = "com.service.CxddCountResponse")
	public int cxddCount();

	/**
	 * 
	 * @param in0
	 * @return returns com.service.ArrayOfQyjbxx
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getQyjbxx", targetNamespace = "http://service.com", className = "com.service.GetQyjbxx")
	@ResponseWrapper(localName = "getQyjbxxResponse", targetNamespace = "http://service.com", className = "com.service.GetQyjbxxResponse")
	public ArrayOfQyjbxx getQyjbxx(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.service.Qysjk
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getQysjk", targetNamespace = "http://service.com", className = "com.service.GetQysjk")
	@ResponseWrapper(localName = "getQysjkResponse", targetNamespace = "http://service.com", className = "com.service.GetQysjkResponse")
	public Qysjk getQysjk(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0);

	/**
	 * 
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "qysjkCount", targetNamespace = "http://service.com", className = "com.service.QysjkCount")
	@ResponseWrapper(localName = "qysjkCountResponse", targetNamespace = "http://service.com", className = "com.service.QysjkCountResponse")
	public int qysjkCount();

	/**
	 * 
	 * @param in1
	 * @param in0
	 * @return returns com.service.ArrayOfSsxx
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getList", targetNamespace = "http://service.com", className = "com.service.GetList")
	@ResponseWrapper(localName = "getListResponse", targetNamespace = "http://service.com", className = "com.service.GetListResponse")
	public ArrayOfSsxx getList(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0,
			@WebParam(name = "in1", targetNamespace = "http://service.com") int in1);

	/**
	 * 
	 * @param in0
	 * @return returns int
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "cxddCount1", targetNamespace = "http://service.com", className = "com.service.CxddCount1")
	@ResponseWrapper(localName = "cxddCount1Response", targetNamespace = "http://service.com", className = "com.service.CxddCount1Response")
	public int cxddCount1(
			@WebParam(name = "in0", targetNamespace = "http://service.com") String in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.service.ArrayOfQygg
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getQygg", targetNamespace = "http://service.com", className = "com.service.GetQygg")
	@ResponseWrapper(localName = "getQyggResponse", targetNamespace = "http://service.com", className = "com.service.GetQyggResponse")
	public ArrayOfQygg getQygg(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0);

	/**
	 * 
	 * @param in0
	 * @return returns com.service.Zjjg
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getZjjgById", targetNamespace = "http://service.com", className = "com.service.GetZjjgById")
	@ResponseWrapper(localName = "getZjjgByIdResponse", targetNamespace = "http://service.com", className = "com.service.GetZjjgByIdResponse")
	public Zjjg getZjjgById(
			@WebParam(name = "in0", targetNamespace = "http://service.com") int in0);
	
	/**
	 * 
	 * @param in0
	 * @return returns com.service.ArrayOfGpgsxq
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getListGpgsxq", targetNamespace = "http://service.com", className = "com.service.GetListGpgsxq")
	@ResponseWrapper(localName = "getListGpgsxqResponse", targetNamespace = "http://service.com", className = "com.service.GetListGpgsxqResponse")
	public ArrayOfGpgsxq getListGpgsxq(
			@WebParam(name = "in0", targetNamespace = "http://service.com") String in0);
	
	
	
	/**
	 * 
	 * @param in0
	 * @return returns com.service.ArrayOfComnotice
	 */
	@WebMethod
	@WebResult(name = "out", targetNamespace = "http://service.com")
	@RequestWrapper(localName = "getListComnotice", targetNamespace = "http://service.com", className = "com.service.GetListComnotice")
	@ResponseWrapper(localName = "getListComnoticeResponse", targetNamespace = "http://service.com", className = "com.service.GetListComnoticeResponse")
	public ArrayOfComnotice getListComnotice(
			@WebParam(name = "in0", targetNamespace = "http://service.com") String in0);

}
